"""Build single-symbol helper projects for the regression harness.

- Cleanup_Regression.apx: removes Universe-Rank static variables before a run.
- Finalize_Ranks.apx: regenerates ranks once, single-threaded, after the scan.

Usage:
    python tools/make_cleanup_apx.py [StrategyCode]

StrategyCode defaults to TPL; it must match StrategyCode in VWAP_01_STRATEGY.afl
(use VWTT for this strategy).
(namespaces the "<code>uniqs_" / "<code>unirank" static vars).
"""

import html
import re
import sys
from pathlib import Path

from apx_codec import encode_formula

ROOT = Path(__file__).resolve().parents[1]
SRC_APX = ROOT / "automation" / "Backtest_Regression.apx"

CLEANUP_AFL = """// GENERATED by tools/make_cleanup_apx.py -- do not edit by hand.
// Regression harness: wipe Universe-Rank static vars before the populate scan.
// See ORB/lessons/regression-gate-determinism.md.
StaticVarRemove("{code}uniqs_*");
StaticVarRemove("{code}unirank*");
StaticVarRemove("{code}uniReady");
Filter = 0;
Buy = Sell = Short = Cover = 0;
"""

FINALIZE_AFL = """// GENERATED by tools/make_cleanup_apx.py -- do not edit by hand.
// Regression harness: deterministic rank finalize after multithreaded scan.
StaticVarGenerateRanks("{code}unirank", "{code}uniqs_", 0, 1224);
StaticVarSet("{code}uniReady", 1, False);
Filter = 0;
Buy = Sell = Short = Cover = 0;
"""

HELPERS = {
    "Cleanup_Regression": CLEANUP_AFL,
    "Finalize_Ranks": FINALIZE_AFL,
}


def build(src: str, name: str, template: str, code: str):
    afl_path = ROOT / "automation" / f"{name}.afl"
    afl_text = template.format(code=code)
    afl_path.write_text(afl_text, encoding="utf-8")

    apx = re.sub(
        r"<FormulaContent>.*?</FormulaContent>",
        lambda _: f"<FormulaContent>{encode_formula(afl_text)}</FormulaContent>",
        src,
        flags=re.S,
    )
    formula_path = f"<FormulaPath>{html.escape(str(afl_path), quote=False)}</FormulaPath>"
    apx = re.sub(r"<FormulaPath>[^<]*</FormulaPath>", lambda _: formula_path, apx)
    apx = apx.replace("<ApplyTo>2</ApplyTo>", "<ApplyTo>1</ApplyTo>")

    dst_apx = ROOT / "automation" / f"{name}.apx"
    dst_apx.write_text(apx, encoding="utf-8")
    print(f"wrote {dst_apx} (code={code}, {len(apx)} chars)")


def main():
    code = sys.argv[1] if len(sys.argv) > 1 else "TPL"
    if not SRC_APX.exists():
        raise SystemExit(f"run make_regression_apx.py first ({SRC_APX} missing)")
    src = SRC_APX.read_text(encoding="utf-8")
    for name, template in HELPERS.items():
        build(src, name, template, code)


if __name__ == "__main__":
    main()
